import Navbar from './components/Navbar';
import './globals.css';

export const metadata = {
  title: 'Fetching movies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-950 h-screen w-screen">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
