import './globals.css'

export const metadata = {
  title: 'Fetching movies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-950 p-6">{children}</body>
    </html>
  )
}
